version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: retail_postgres
    restart: always
    environment:
      POSTGRES_DB: retail_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ingestion-service:
    build:
      context: ./Ingestion-Service
    container_name: ingestion_service
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DB_HOST: postgres
      DB_NAME: retail_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  processing-service:
    build:
      context: ./Processing-Service
    container_name: processing_service
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DB_HOST: postgres
      DB_NAME: retail_db
      DB_USER: postgres
      DB_PASSWORD: postgres
